[package]
name = "revpfw3"
repository = "https://github.com/tudbut/revpfw3"
desciption = "A tool to bypass portforwarding restrictions using some cheap VServer"
license = "MIT"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-ordinalize = "3.1"
